# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michael/Desktop/code/C++/OpenGL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michael/Desktop/code/C++/OpenGL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/Desktop/code/C++/OpenGL/CMakeFiles /home/michael/Desktop/code/C++/OpenGL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/Desktop/code/C++/OpenGL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pit-smellers

# Build rule for target.
pit-smellers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pit-smellers
.PHONY : pit-smellers

# fast build rule for target.
pit-smellers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/build
.PHONY : pit-smellers/fast

src/GameEngine/collision.o: src/GameEngine/collision.cpp.o
.PHONY : src/GameEngine/collision.o

# target to build an object file
src/GameEngine/collision.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GameEngine/collision.cpp.o
.PHONY : src/GameEngine/collision.cpp.o

src/GameEngine/collision.i: src/GameEngine/collision.cpp.i
.PHONY : src/GameEngine/collision.i

# target to preprocess a source file
src/GameEngine/collision.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GameEngine/collision.cpp.i
.PHONY : src/GameEngine/collision.cpp.i

src/GameEngine/collision.s: src/GameEngine/collision.cpp.s
.PHONY : src/GameEngine/collision.s

# target to generate assembly for a file
src/GameEngine/collision.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GameEngine/collision.cpp.s
.PHONY : src/GameEngine/collision.cpp.s

src/GameEngine/physics.o: src/GameEngine/physics.cpp.o
.PHONY : src/GameEngine/physics.o

# target to build an object file
src/GameEngine/physics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GameEngine/physics.cpp.o
.PHONY : src/GameEngine/physics.cpp.o

src/GameEngine/physics.i: src/GameEngine/physics.cpp.i
.PHONY : src/GameEngine/physics.i

# target to preprocess a source file
src/GameEngine/physics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GameEngine/physics.cpp.i
.PHONY : src/GameEngine/physics.cpp.i

src/GameEngine/physics.s: src/GameEngine/physics.cpp.s
.PHONY : src/GameEngine/physics.s

# target to generate assembly for a file
src/GameEngine/physics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GameEngine/physics.cpp.s
.PHONY : src/GameEngine/physics.cpp.s

src/GameEngine/player.o: src/GameEngine/player.cpp.o
.PHONY : src/GameEngine/player.o

# target to build an object file
src/GameEngine/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GameEngine/player.cpp.o
.PHONY : src/GameEngine/player.cpp.o

src/GameEngine/player.i: src/GameEngine/player.cpp.i
.PHONY : src/GameEngine/player.i

# target to preprocess a source file
src/GameEngine/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GameEngine/player.cpp.i
.PHONY : src/GameEngine/player.cpp.i

src/GameEngine/player.s: src/GameEngine/player.cpp.s
.PHONY : src/GameEngine/player.s

# target to generate assembly for a file
src/GameEngine/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GameEngine/player.cpp.s
.PHONY : src/GameEngine/player.cpp.s

src/GameEngine/weapon.o: src/GameEngine/weapon.cpp.o
.PHONY : src/GameEngine/weapon.o

# target to build an object file
src/GameEngine/weapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GameEngine/weapon.cpp.o
.PHONY : src/GameEngine/weapon.cpp.o

src/GameEngine/weapon.i: src/GameEngine/weapon.cpp.i
.PHONY : src/GameEngine/weapon.i

# target to preprocess a source file
src/GameEngine/weapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GameEngine/weapon.cpp.i
.PHONY : src/GameEngine/weapon.cpp.i

src/GameEngine/weapon.s: src/GameEngine/weapon.cpp.s
.PHONY : src/GameEngine/weapon.s

# target to generate assembly for a file
src/GameEngine/weapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GameEngine/weapon.cpp.s
.PHONY : src/GameEngine/weapon.cpp.s

src/GraphicsEngine/camera.o: src/GraphicsEngine/camera.cpp.o
.PHONY : src/GraphicsEngine/camera.o

# target to build an object file
src/GraphicsEngine/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GraphicsEngine/camera.cpp.o
.PHONY : src/GraphicsEngine/camera.cpp.o

src/GraphicsEngine/camera.i: src/GraphicsEngine/camera.cpp.i
.PHONY : src/GraphicsEngine/camera.i

# target to preprocess a source file
src/GraphicsEngine/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GraphicsEngine/camera.cpp.i
.PHONY : src/GraphicsEngine/camera.cpp.i

src/GraphicsEngine/camera.s: src/GraphicsEngine/camera.cpp.s
.PHONY : src/GraphicsEngine/camera.s

# target to generate assembly for a file
src/GraphicsEngine/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GraphicsEngine/camera.cpp.s
.PHONY : src/GraphicsEngine/camera.cpp.s

src/GraphicsEngine/lightsource.o: src/GraphicsEngine/lightsource.cpp.o
.PHONY : src/GraphicsEngine/lightsource.o

# target to build an object file
src/GraphicsEngine/lightsource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GraphicsEngine/lightsource.cpp.o
.PHONY : src/GraphicsEngine/lightsource.cpp.o

src/GraphicsEngine/lightsource.i: src/GraphicsEngine/lightsource.cpp.i
.PHONY : src/GraphicsEngine/lightsource.i

# target to preprocess a source file
src/GraphicsEngine/lightsource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GraphicsEngine/lightsource.cpp.i
.PHONY : src/GraphicsEngine/lightsource.cpp.i

src/GraphicsEngine/lightsource.s: src/GraphicsEngine/lightsource.cpp.s
.PHONY : src/GraphicsEngine/lightsource.s

# target to generate assembly for a file
src/GraphicsEngine/lightsource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GraphicsEngine/lightsource.cpp.s
.PHONY : src/GraphicsEngine/lightsource.cpp.s

src/GraphicsEngine/model.o: src/GraphicsEngine/model.cpp.o
.PHONY : src/GraphicsEngine/model.o

# target to build an object file
src/GraphicsEngine/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GraphicsEngine/model.cpp.o
.PHONY : src/GraphicsEngine/model.cpp.o

src/GraphicsEngine/model.i: src/GraphicsEngine/model.cpp.i
.PHONY : src/GraphicsEngine/model.i

# target to preprocess a source file
src/GraphicsEngine/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GraphicsEngine/model.cpp.i
.PHONY : src/GraphicsEngine/model.cpp.i

src/GraphicsEngine/model.s: src/GraphicsEngine/model.cpp.s
.PHONY : src/GraphicsEngine/model.s

# target to generate assembly for a file
src/GraphicsEngine/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GraphicsEngine/model.cpp.s
.PHONY : src/GraphicsEngine/model.cpp.s

src/GraphicsEngine/renderer.o: src/GraphicsEngine/renderer.cpp.o
.PHONY : src/GraphicsEngine/renderer.o

# target to build an object file
src/GraphicsEngine/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GraphicsEngine/renderer.cpp.o
.PHONY : src/GraphicsEngine/renderer.cpp.o

src/GraphicsEngine/renderer.i: src/GraphicsEngine/renderer.cpp.i
.PHONY : src/GraphicsEngine/renderer.i

# target to preprocess a source file
src/GraphicsEngine/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GraphicsEngine/renderer.cpp.i
.PHONY : src/GraphicsEngine/renderer.cpp.i

src/GraphicsEngine/renderer.s: src/GraphicsEngine/renderer.cpp.s
.PHONY : src/GraphicsEngine/renderer.s

# target to generate assembly for a file
src/GraphicsEngine/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/GraphicsEngine/renderer.cpp.s
.PHONY : src/GraphicsEngine/renderer.cpp.s

src/include/stb_image/stb_image.o: src/include/stb_image/stb_image.cpp.o
.PHONY : src/include/stb_image/stb_image.o

# target to build an object file
src/include/stb_image/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/include/stb_image/stb_image.cpp.o
.PHONY : src/include/stb_image/stb_image.cpp.o

src/include/stb_image/stb_image.i: src/include/stb_image/stb_image.cpp.i
.PHONY : src/include/stb_image/stb_image.i

# target to preprocess a source file
src/include/stb_image/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/include/stb_image/stb_image.cpp.i
.PHONY : src/include/stb_image/stb_image.cpp.i

src/include/stb_image/stb_image.s: src/include/stb_image/stb_image.cpp.s
.PHONY : src/include/stb_image/stb_image.s

# target to generate assembly for a file
src/include/stb_image/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/include/stb_image/stb_image.cpp.s
.PHONY : src/include/stb_image/stb_image.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pit-smellers.dir/build.make CMakeFiles/pit-smellers.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pit-smellers"
	@echo "... src/GameEngine/collision.o"
	@echo "... src/GameEngine/collision.i"
	@echo "... src/GameEngine/collision.s"
	@echo "... src/GameEngine/physics.o"
	@echo "... src/GameEngine/physics.i"
	@echo "... src/GameEngine/physics.s"
	@echo "... src/GameEngine/player.o"
	@echo "... src/GameEngine/player.i"
	@echo "... src/GameEngine/player.s"
	@echo "... src/GameEngine/weapon.o"
	@echo "... src/GameEngine/weapon.i"
	@echo "... src/GameEngine/weapon.s"
	@echo "... src/GraphicsEngine/camera.o"
	@echo "... src/GraphicsEngine/camera.i"
	@echo "... src/GraphicsEngine/camera.s"
	@echo "... src/GraphicsEngine/lightsource.o"
	@echo "... src/GraphicsEngine/lightsource.i"
	@echo "... src/GraphicsEngine/lightsource.s"
	@echo "... src/GraphicsEngine/model.o"
	@echo "... src/GraphicsEngine/model.i"
	@echo "... src/GraphicsEngine/model.s"
	@echo "... src/GraphicsEngine/renderer.o"
	@echo "... src/GraphicsEngine/renderer.i"
	@echo "... src/GraphicsEngine/renderer.s"
	@echo "... src/include/stb_image/stb_image.o"
	@echo "... src/include/stb_image/stb_image.i"
	@echo "... src/include/stb_image/stb_image.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

