#pragma once


enum StateType        { STATE_PHYSICS, STATE_NAVIGATION };

enum PhysicsState     { PHYSICS_NONE, PHYSICS_GROUNDED, PHYSICS_FALLING };
enum NavigationState  { NAVIGATION_NONE, NAVIGATION_REST, NAVIGATION_SEEK };
